### ISSUE TITLE
Dashboard page - make Navbar button clicked by default for desktop, unclicked by default for mobile phones

### ISSUE THREAD

**Issue by krashish8** [Spardha-IIT-BHU/Spardha21-Website#34]
![image](https://user-images.githubusercontent.com/39548570/159003672-e3e25800-ad2f-46a1-a833-b0ef06ae29b4.png)

For desktop, please make this button clicked by default in all the Dashboard pages, so that sidebar is visible when the user logs in.

And in mobile mode, make this button unclicked by default so that the navbar is not shown always when moving to any other Dashboard page.

@Spardha-IIT-BHU/team-2022

**Comment by SanidhyaTaparia** [comment]
Done for both mobile and desktop view
